### ISSUE TITLE
this.super would not work in consequent calls

### ISSUE THREAD

**Issue by abozhilov** [astoilkov/jsblocks#3]
You always start resolution of super from the `this`, so you can trap in infinite recursion. 
e.g 

Class1 
    method

Class2 extends Class1
   method -> here we have this.super('method')

Class3 extends Class2
   method -> here we have this.super('method')

inst = new Class3().method(); 

When you call this.super('method') in Class3 you will indeed call the Class2.method but there this will refer `inst` object. So when you try to call super again the resolution will be again Class2.method. 

The best fix of this is to not use it at all.

**Comment by astoilkov** [comment]
I have fixed the issue. Actually the relevant code is in the [jscore repo](https://github.com/astoilkov/jscore) repo. Here is the relevant commit: 
https://github.com/astoilkov/jscore/commit/6acf89ef6a10463b39d0cef7a52958a063cc7dd4

**Comment by abozhilov** [comment]
This fixes the particular issue with infinite recursion, but it doesn't fix the problems with `super`. Now if you have the following prototype chain: 
```
A ->
  method 
B ->
  method - call super method
C -> there is no definition of method
D -> 
  method - call super method
```

Now you will have two calls of B->method according to your fix. 

Next bug: indirect recursion is impossible with that approach: 

```
A -> 
    method - which calls this.test()
B -> 
   method 
   test - calls this.super('method') 
```

Even this is stupid design the proper implementation of super should work as expected. Better leave this super implementation, JS has good enough approach for invoking "super" methods, constructors.

**Comment by astoilkov** [comment]
You are correct. I was actually using this in way simpler ways internally. Do you have any suggestions for fixing the problem? If not I will remove the method for now.

**Comment by abozhilov** [comment]
From what I know, there is no sophisticated approach of `this.super` in JS. All of the approaches suffer either from too much memory consumption and redundancy or buggy implementation. The best decision is to remove that from your API. IIRC ES6 comes with classes and `super` implementation.
